In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
df=pd.read_csv('/content/Bank_Personal_Loan_Modelling.csv')
df

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0            0              0                   1           0       0   
1            0              0                   1           0       0   
2            0              0                   0           0       0   
3            0              0                   0           0       0   
4            0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [ ]:
df.head()#first 5 rows

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [ ]:
df.tail() #last 5 rows

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1

In [ ]:
df.describe

<bound method NDFrame.describe of         ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  On

In [ ]:
df.isna().sum() #total missing value

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [ ]:
df.drop_duplicates()#remove duplicate values

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0            0              0                   1           0       0   
1            0              0                   1           0       0   
2            0              0                   0           0       0   
3            0              0                   0           0       0   
4            0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [ ]:
df.drop(['ID'],axis=True)#drop id
df.drop(['ZIP Code'],axis=True)

ID  Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
0        1   25           1      49       4    1.6          1         0   
1        2   45          19      34       3    1.5          1         0   
2        3   39          15      11       1    1.0          1         0   
3        4   35           9     100       1    2.7          2         0   
4        5   35           8      45       4    1.0          2         0   
...    ...  ...         ...     ...     ...    ...        ...       ...   
4995  4996   29           3      40       1    1.9          3         0   
4996  4997   30           4      15       4    0.4          1        85   
4997  4998   63          39      24       2    0.3          3         0   
4998  4999   65          40      49       3    0.5          2         0   
4999  5000   28           4      83       3    0.8          1         0   

      Personal Loan  Securities Account  CD Account  Online  CreditCard  
0                 0                   1           0       0           0  
1                 0                   1           0       0           0  
2                 0                   0           0       0           0  
3                 0                   0           0       0           0  
4                 0                   0           0       0           1  
...             ...                 ...         ...     ...         ...  
4995              0                   0           0       1           0  
4996              0                   0           0       1           0  
4997              0                   0           0       0           0  
4998              0                   0           0       1           0  
4999              0                   0           0       1           1  

[5000 rows x 13 columns]

In [ ]:
x=df.iloc[:,:-1].values
x

array([[1.000e+00, 2.500e+01, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [2.000e+00, 4.500e+01, 1.900e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [3.000e+00, 3.900e+01, 1.500e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [4.998e+03, 6.300e+01, 3.900e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [4.999e+03, 6.500e+01, 4.000e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [5.000e+03, 2.800e+01, 4.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [ ]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 0, 1])

#training and testing data preperation

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[1.841e+03, 5.500e+01, 2.500e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.116e+03, 5.700e+01, 3.100e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [4.438e+03, 6.300e+01, 3.800e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       ...,
       [3.093e+03, 4.300e+01, 1.800e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [3.773e+03, 3.500e+01, 1.000e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [8.610e+02, 5.700e+01, 3.100e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

#normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
x_test

array([[0.29913845, 0.15909091, 0.15217391, ..., 1.        , 0.        ,
        0.        ],
       [0.51652975, 0.54545455, 0.56521739, ..., 0.        , 0.        ,
        0.        ],
       [0.52995392, 0.15909091, 0.17391304, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.36645963, 0.45454545, 0.45652174, ..., 0.        , 0.        ,
        1.        ],
       [0.47525546, 0.38636364, 0.41304348, ..., 0.        , 0.        ,
        0.        ],
       [0.38148668, 0.43181818, 0.41304348, ..., 1.        , 1.        ,
        1.        ]])

#model creation

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

knn=KNeighborsClassifier(n_neighbors=11)
navie=MultinomialNB()
smv=SVC()
lst=[knn,navie,smv]



# **performance Evaluation**

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
for i in lst:
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  y_pred
  print('Acuracy score is',accuracy_score(y_test,y_pred))
  print("*"*10)
  print('confusion_metrix',confusion_matrix(y_test,y_pred))
  print('*'*10)
  print('classification',classification_report(y_test,y_pred))

Acuracy score is 0.7286666666666667
**********
confusion_metrix [[1001   72]
 [ 335   92]]
**********
classification               precision    recall  f1-score   support

           0       0.75      0.93      0.83      1073
           1       0.56      0.22      0.31       427

    accuracy                           0.73      1500
   macro avg       0.66      0.57      0.57      1500
weighted avg       0.70      0.73      0.68      1500

Acuracy score is 0.7493333333333333
**********
confusion_metrix [[1053   20]
 [ 356   71]]
**********
classification               precision    recall  f1-score   support

           0       0.75      0.98      0.85      1073
           1       0.78      0.17      0.27       427

    accuracy                           0.75      1500
   macro avg       0.76      0.57      0.56      1500
weighted avg       0.76      0.75      0.69      1500

Acuracy score is 0.7546666666666667
**********
confusion_metrix [[1065    8]
 [ 360   67]]
**********
classifica

In [16]:
from  sklearn.metrics import precision_recall_curve
curv=precision_recall_curve(y_test,y_pred)
curv

(array([0.28466667, 0.89333333, 1.        ]),
 array([1.        , 0.15690867, 0.        ]),
 array([0, 1]))